//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCI_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUserCustomer
    {
        public string ApplicationUser_Id { get; set; }
        public int Customer_CustomerID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
